/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Cart: typeof import('./src/components/Cart.vue')['default']
    CheckMark: typeof import('./src/components/CheckMark.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElPopconfirm: typeof import('element-plus/es')['ElPopconfirm']
    HeadImg: typeof import('./src/components/HeadImg.vue')['default']
    Index: typeof import('./src/components/Index.vue')['default']
    Mall: typeof import('./src/components/Mall.vue')['default']
    NavBall: typeof import('./src/components/NavBall.vue')['default']
    NavBar: typeof import('./src/components/NavBar.vue')['default']
    Orders: typeof import('./src/components/Orders.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Setting: typeof import('./src/components/Setting.vue')['default']
    Signin: typeof import('./src/components/Signin.vue')['default']
    SigninSignup: typeof import('./src/components/SigninSignup.vue')['default']
    Signup: typeof import('./src/components/Signup.vue')['default']
  }
}
