server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/item?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: commander
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.jdbc.Driver


path:
  image: D:/Git/superSFProgram/springmvc-img-data/img-super-puls7-team/